apiVersion: v1
kind: Service

metadata:
  name: ms-api-gateway

spec:
  selector:
    app: ms-api-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30001
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-api-gateway
spec:
  selector:
    matchLabels:
      app: ms-api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-api-gateway
    spec:
      containers:
        - name: ms-api-gateway
          image: rohitphular/api-gateway:local-latest