server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: partner-service
          uri: http://localhost:9001
          predicates:
            - Path=/api/partner/**
        - id: search-service
          uri: http://localhost:9002
          predicates:
            - Path=/api/search/**